### ISSUE TITLE
Cosmetic improvements on figures

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#35]
Todo:
- Add `ManufacturersModelName` embedded in each bar
- Add within-vendor stats as dashed line (mean) and transparent rectangle (std), and display mean+-std (cov)
- Add small flag of country for each site

See below a prototype (made with Keynote):
![Screen Shot 2019-05-05 at 14 57 15](https://user-images.githubusercontent.com/2482071/57199318-8cfafc80-6f4b-11e9-90b7-e668d9802f28.png)

**Comment by charleygros** [comment]
For the flag of each flag, I see two main options:

1. Save the flags (images) in a folder and use a function like:
```
def get_flag(name):
    path = "path/to/flag/{}.png".format(name)
    im = plt.imread(path)
    return im
```

2. Use this package:
https://pypi.org/project/emoji/

@jcohenadad : Do you have a preference?

**Comment by jcohenadad** [comment]
The emoji option sounds easier

**Comment by charleygros** [comment]
I tried the emoji approach.

1. Create a flag dictionary:
```
flags = {
        'cardiff': ':flag-uk:',
        'geneva': ':flag-ch:',
        'hamburg': ':flag-de:',
}
```

2. Use the `emoji` package:
```
xtick_sorted = [emoji.emojize(flags[s], use_aliases=True) + ' ' + s for s in site_sorted]
```

3. In `matplotlib`:
```
ax.set_xticklabels(xtick_sorted)
```

Results:
![1](https://user-images.githubusercontent.com/14353425/57338129-982e7200-716f-11e9-9c47-31408acd6f54.png)

Keep investigating :flag-up:
