### ISSUE TITLE
Homogeneize ManufacturersModelName in dataset_description.json

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#36]
The field `ManufacturersModelName` in the file `dataset_description.json` is not consistent. E.g., there could be `Prisma-fit` or `Prisma_fit`. 

This causes issues when gathering results and should be fixed.

**Comment by alexfoias** [comment]
It's fixed for data under `duke/sct_testing/bids/spineGeneric_multiSubjects`

**Comment by jcohenadad** [comment]
it is also fixed in `duke/sct_testing/bids_spineGeneric_multiSubjects_aggregated`
