### ISSUE TITLE
Create a function that generates a mosaic of 2D images

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#39]
To display the variability of image quality across sites, it would be nice to make a function that automatically creates a mosaic of images.

Those images (3d volumes) could be selected as input param of the function. The function would select the mid sagittal (or axial) slice, and then create a mosaic of A x B (could be specified as input param).

**Comment by charleygros** [comment]
@jcohenadad : Great idea!

Few immediate questions:
- Axial slices: full slice or cropped around the SC (as done in the sct_qc)? We will need to input the segmentation as well if we want them to be cropped.
- Mosaic A x B --> A slices (evenly spaced) x B 3d volumes?
- impose common intensity scale for all samples? or do we want to display this heterogeneity?

**Comment by jcohenadad** [comment]
Axial: cropped around the cord (reuse func from reports/qc. Only show midslice 
AxB: example: 1000x600 pixels 
I was thinking of applying CLAHE filter (already implemented in qc)

**Comment by Nicolas-Pinon** [comment]
@jcohenadad to the question :
>     * Mosaic A x B --> A slices (evenly spaced) x B 3d volumes?
you responded : 
> AxB: example: 1000x600 pixels
I am not sure I understand the response, should we do a A x B mosaic where A is the number of slices (if axial) and B the number of inputed images ?

**Comment by jcohenadad** [comment]
> I am not sure I understand the response, should we do a A x B mosaic where A is the number of slices (if axial) and B the number of inputed images ?

you don't care about the number of slices. Only show the mid-slice (i.e. one slice per subject)

**Comment by charleygros** [comment]
Fixed by [PR41](https://github.com/sct-pipeline/spine-generic/pull/41)
