### ISSUE TITLE
Prepare multi-subject v1.0.6 on openneuro

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#70]
- Update authors as per table on manuscript generic
- Upload defaced images
- Fix CHANGES
- Fix name for brno sites

**Comment by alexfoias** [comment]
@jcohenadad Can I go ahead an upload 1.0.6 ?

**Comment by jcohenadad** [comment]
> Renamed centers brno → UHBrno, brnoPrisma → CEITECBrno

not what we decided, please see: https://github.com/sct-pipeline/spine-generic/pull/55

Also, the procedure above seems overly-complicated-- why maintaining two repository locally (faced + defaced) before updating to openneuro, which is more prone to errors. 

Also, I would update openneuro with only the defaced data as a first step (1.0.6), before making other changes, so it is easier for us to verify the diff. Once everything is correct, we can proceed to another snapshot (1.0.7):

* Propagate the change spineGeneric_multiSubjects/ → spineGeneric_multiSubjects_defaced/
`rsync -av --progress duke/sct_testing/bids/spineGeneric_multiSubjects/ duke/sct_testing/bids/spineGeneric_multiSubjects_defaced/`
* `mv duke/sct_testing/bids/spineGeneric_multiSubjects duke/sct_testing/bids/spineGeneric_multiSubjects_DONOTUSE` → will be deleted after the procedure is completed
* `mv duke/sct_testing/bids/spineGeneric_multiSubjects_defaced duke/sct_testing/bids/spineGeneric_multiSubjects` → is the new local reference
* Remove the "defaced" term in spineGeneric_multiSubjects
* Fix CHANGES to include history from 1.0.0 to 1.0.5.
* Update to openneuro as snapshot 1.0.6, keep the log. When prompted to list changes, indicate:
    * Replaced T1w and T2w with defaced data
    * Fixed CHANGES to include history from 1.0.0 to 1.0.5.
* We make sure everything is correct.

If everything is correct:
* Rename brno data
* Update coauthors
* Update to openneuro as snapshot 1.0.7, keep the log.

Please carefully review this procedure to make sure I did not forget anything.

**Comment by alexfoias** [comment]
Yes, I agree with your roadmap. It seems fine to me. I updated the author list already on the website this morning and there's no way of dropping the changes. I'll just indicated in the CHANGES and than update if other people put their name on the list.

**Comment by alexfoias** [comment]
Here are the log files of the transfer.
The initial upload that failed: [log_upload-20200605-1140.txt](https://github.com/sct-pipeline/spine-generic/files/4747580/log_upload-20200605-1140.txt)
The upload that worked: [log_upload-20200608-1205.txt](https://github.com/sct-pipeline/spine-generic/files/4747581/log_upload-20200608-1205.txt)

**Comment by jcohenadad** [comment]
- for the one that worked: how come the files that are supposed to be updated show a “skipped” message?
- you uploaded .DS_Store files. It was already clear in the procedure that you should not upload those files.

**Comment by alexfoias** [comment]
This issue can be closed.

**Comment by jcohenadad** [comment]
snapshot created here: https://openneuro.org/datasets/ds001919/versions/1.0.6
