### ISSUE TITLE
Prepare single-subject v1.0.3 on openneuro

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#71]
Changes that have to be mentioned in CHANGES:

- Updated site names to match convention for multi-subject (mghBay3 → mgh; oxford → oxfordFmrib)
- Updated acknowledgements
- Changed the list of authors
- Fixed CHANGES in descending order

**Comment by alexfoias** [comment]
@jcohenadad In order to match the convention, we'll have to name them like this:
```
mghBay3 → mgh
oxford → oxfordFmrib
```

**Comment by alexfoias** [comment]
@jcohenadad Do we have specific acknowledgements for single-subject ? or should I grab the ones from multi-subject ?

**Comment by jcohenadad** [comment]
where would the acknowledgements be located?

**Comment by alexfoias** [comment]
that section is part of dataset_description.json and it will be rendered on the webpage after lincense section.

**Comment by jcohenadad** [comment]
~~~
We thank Alexandru Foias (Polytechnique Montreal) for database management and image processing, Drs. Gerald Moran and Bart Schraa (Siemens Healthcare), Drs. Suchandrima Banerjee and Naoyuki Takei (GE Healthcare) and Dr. Guillaume Gilbert (Philips Healthcare) for consultation on vendor-specific questions, and Carollyn Hurst, André Cyr, Arnaud Boré and Dr. Pierre Bellec (Functional Neuroimaging Unit), Charles Tremblay (Polytechnique Montreal), Antonys Melek and Dr. Habib Benali (PERFORM center, Concordia University), Dr. Ives Levesque (McGill University), Dr. Jamie Near (Douglas Hospital), Dr. Robert Barry (MGH Martinos Center), Dr. Johanna Vannesjo (Oxford University), Drs. Claudia Gandini Wheeler-Kingshott, Francesco Grussu, Rebecca Samson and Marios Yiannakas (UCL), Dr. Satoshi Maki (Chiba University Hospital), Dr. Shigeki Aoki, Dr. Masaaki Hori, Dr. Akifumi Hagiwara, Issei Fukunaga (Juntendo University), Dr. Kouhei Kamiya, Y. Suzuki (Tokyo University) for helping with data acquisition.
~~~

**Comment by alexfoias** [comment]
@jcohenadad I did the changes noted above. Can I go ahead and upload to openneuro 1.0.3 ?

**Comment by jcohenadad** [comment]
- also change the list of authors (it has a "test" author) (update the list of CHANGES at the beginning of this thread)
- i've renamed this issue to be consistent

**Comment by alexfoias** [comment]
the changes are made for the authors.

**Comment by alexfoias** [comment]
This issue can be closed. Snapshot 1.0.3 can be found here: https://openneuro.org/datasets/ds002393/versions/1.0.3
