### ISSUE TITLE
Prepare multi-subject v1.0.7 on openneuro

### ISSUE THREAD

**Issue by alexfoias** [sct-pipeline/spine-generic#74]
@jcohenadad Here is the plan 

Changes that have to be made and mentioned in CHANGES for snapshot 1.0.7:
- Renamed brno data (brno → brnoUhb & brnoPrisma → brnoCeitec)
- Updated coauthors
- Fixed CHANGES to descending order

Upload procedure listed here: https://github.com/sct-pipeline/spine-generic/wiki/upload-to-openneuro. 

In the SOP you said : _Save log file in new release of this repository. The tag of the repository should be the same release as in openeuro_ . Do you want to upload that log to openneuro ? or just keep it local ?

**Comment by jcohenadad** [comment]
@alexfoias i think you can go ahead with 1.0.7, thanks

**Comment by alexfoias** [comment]
Sounds good so the correct list of authors for multi-center is in https://docs.google.com/document/d/1jEWCrZ2eoHWSVDoVRjxs53-Z7vUcjhlo3yYsM45XFEQ/edit ?

**Comment by alexfoias** [comment]
@jcohenadad I did all the changes and I added the authors as in the manuscript_copy. Can I go ahead and upload it to openneuro ?

**Comment by alexfoias** [comment]
Uploaded on https://openneuro.org/datasets/ds001919/versions/1.0.7

**Comment by alexfoias** [comment]
This issue can be closed.
