### ISSUE TITLE
Prepare multi-subject v1.0.8 on openneuro

### ISSUE THREAD

**Issue by alexfoias** [sct-pipeline/spine-generic#75]
Changes that have to be mentioned in CHANGES:
- Added data from mountSinai
- vuiisIngenia changed scanner type to Philips, Ingenia
- Removed duplicated authors
- Removed authors not listed in the manuscript table (e.g. Prados)
- Added empty paragraph before the latest entry
- Fixed acknowledgements (https://github.com/sct-pipeline/spine-generic/issues/77)

**Comment by jcohenadad** [comment]
> Added empty paragraph before the latest entry

@alexfoias can you elaborate?

**Comment by alexfoias** [comment]
The webpages adds the changes directly after the latest entry (1.0.6). Or if you want we can keep it without empty paragrapgh, but it makes it harder to read. 
![Screen Shot 2020-06-11 at 4 25 35 PM](https://user-images.githubusercontent.com/12564433/84435666-3527ce00-ac00-11ea-9079-88616e11147e.png)

The content for 1.0.7 was added by their system.

**Comment by alexfoias** [comment]
@jcohenadad I did the changes and I rechecked the authors. Can I go ahead and upload 1.0.8 ?

**Comment by jcohenadad** [comment]
no, let's wait to add data from NY (i'm currently downloading them)

**Comment by jcohenadad** [comment]
@alexfoias fyi i've updated the list at the top (and also reorder from order of importance: top: most important)

**Comment by alexfoias** [comment]
Uploaded the dataset with the changes, but couldn't produce snapshot. https://neurostars.org/t/snapshot-error-ds001919/7168

**Comment by jcohenadad** [comment]
@alexfoias pls follow-up with release and everything that goes with it

**Comment by alexfoias** [comment]
snapshot created here: https://openneuro.org/datasets/ds001919/versions/1.0.8

**Comment by alexfoias** [comment]
new release here: https://github.com/sct-pipeline/spine-generic/releases/tag/v1.2
