### ISSUE TITLE
Multi-subject openneuro: fix in ack: Ives Lesveques → Ives Levesque

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#77]

**Comment by alexfoias** [comment]
will be addressed in https://github.com/sct-pipeline/spine-generic/issues/75

**Comment by evaalonsoortiz** [comment]
It is _Levesque_

**Comment by alexfoias** [comment]
thanks Eva.

**Comment by alexfoias** [comment]
Fixed in snapshot created here: https://openneuro.org/datasets/ds001919/versions/1.0.8
