### ISSUE TITLE
notdefined $PATH_LOG variable 

### ISSUE THREAD

**Issue by valosekj** [sct-pipeline/spine-generic#81]
`$PATH_LOG` variable is not defined when this repo no longer contains `parameter.sh` file?

https://github.com/sct-pipeline/spine-generic/blob/65658e08a37c9834d0083d29455c6f0f50205aea/processing/process_data.sh#L287

**Comment by jcohenadad** [comment]
generated by `sct_run_batch`: https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_run_batch.py#L123

**Comment by jcohenadad** [comment]
there is a default, but you can specify one upon calling the function
