### ISSUE TITLE
Prepare single-subject v1.0.4 on openneuro 

### ISSUE THREAD

**Issue by alexfoias** [sct-pipeline/spine-generic#82]
Changes that have to be mentioned in CHANGES:
- Added defaced T1w and T2w

**Comment by alexfoias** [comment]
@jcohenadad Could you please the QC on the single-subject dehaced located here `duke/sct_testing/bids/spineGeneric_singleSubject_qc_defaced` ?

I would like to include single-subject 1.0.4 to the new release of spine generic.

**Comment by jcohenadad** [comment]
> @jcohenadad Could you please assess the QC on the single-subject defaced located here `duke/sct_testing/bids/spineGeneric_singleSubject_qc_defaced` ?
> 
> I would like to include single-subject 1.0.4 to the new release of spine generic.

looks good!

**Comment by jcohenadad** [comment]
next time you can upload the qc here, for tracability

**Comment by alexfoias** [comment]
yes. for sure i'll do. 

QC in zip format here: [spineGeneric_singleSubject_qc_defaced.zip](https://github.com/sct-pipeline/spine-generic/files/4794676/spineGeneric_singleSubject_qc_defaced.zip)

**Comment by alexfoias** [comment]
@jcohenadad Here is the plan. Similar to https://github.com/sct-pipeline/spine-generic/issues/70
- Propagate the change spineGeneric_singleSubject/ → spineGeneric__singleSubject_defaced/
`rsync -av --progress duke/sct_testing/bids/spineGeneric_singleSubject/ duke/sct_testing/bids/spineGeneric_singleSubject_defaced/`
- `mv duke/sct_testing/bids/spineGeneric_singleSubject duke/sct_testing/bids/spineGeneric_singleSubject_DONOTUSE` → will be deleted after the procedure is completed
- `mv duke/sct_testing/bids/spineGeneric_singleSubject_defaced duke/sct_testing/bids/spineGeneric_singleSubject` → is the new local reference
- Remove the "defaced" term in spineGeneric_singleSubject
- Update to openneuro as snapshot 1.0.4, keep the log. When prompted to list changes, indicate:
Replaced T1w and T2w with defaced data
- We make sure everything is correct.

Please note that step one was done before defacing. 
Please let me know if I can go ahead and propagate the changes.

**Comment by alexfoias** [comment]
snapshot created here: https://openneuro.org/datasets/ds002393/versions/1.0.4
