### ISSUE TITLE
Warnings 

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#83]
on: https://openneuro.org/datasets/ds002900/versions/1.0.1

![Screen Shot 2020-06-19 at 10 41 59 AM](https://user-images.githubusercontent.com/2482071/85144751-97dd2300-b219-11ea-8f1d-21c5fb2b4cec.png)

**Comment by alexfoias** [comment]
Fixed in https://openneuro.org/datasets/ds002900/versions/1.0.2.

I'll generate a new release.

**Comment by alexfoias** [comment]
New release published [here](https://github.com/sct-pipeline/spine-generic/releases/tag/v2.1).
