### ISSUE TITLE
date_of_scan info missing in participants.tsv

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#90]
concerns the single-subject dataset https://openneuro.org/datasets/ds002900

**Comment by valosekj** [comment]
It looks that only `sub-perform ` contains info about date of scan (`AcquisitionDateTime` tag) in json sidecars. Remaining subjects contain only `AcquisitionTime` tag.

**Comment by jcohenadad** [comment]
ah that's too bad 😞 . Thanks for looking into it @valosekj

**Comment by jcohenadad** [comment]
fixed in https://openneuro.org/datasets/ds002900/versions/1.0.3
